### ISSUE TITLE
Unknown props `onSortChange`, `sortDir` on <div> tag.

### ISSUE THREAD

**Issue by jibees** [facebook/fixed-data-table#453]
Hi,
Just see a React warning when using the last version of fixed-data-table (ie. 0.6.3) and React (ie. 15.3.1)
`Unknown props `onSortChange`, `sortDir` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
in div (created by FixedDataTableCellDefault)
...
`

Thanks !

**Comment by KamranAsif** [comment]
Hmm this might be a bug in your code. Can you paste the full stacktrace?

**Comment by jibees** [comment]
Yes, sure:
`console.js:26Warning: Unknown props `onSortChange`, `sortDir` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by SortHeaderCell)
    in SortHeaderCell (created by ContentDBApp)
    in div (created by FixedDataTableCell)
    in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
    in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by TransitionTable)
    in TransitionTable (created by ContentDBApp)
    in div (created by ContentDBApp)
    in div (created by ContentDBApp)
    in div (created by ContentDBApp)
    in ContentDBApp`

ContentDBApp is my component

**Comment by wcjordan** [comment]
@jibees I'm assuming you're making use of the SortHeaderCell example code.  This bug appears to be in there.  Where it [consumes the props](https://github.com/schrodinger/fixed-data-table-2/blob/b4394d1b526a5a53888abe9c2dcac1c0b57e92d0/examples/SortExample.js#L30), it doesn't consume onSortChange when it should.  It does appear to consume sortDir though so I'm not sure why you're seeing that as an error, unless it's fixed on FDT2 but not FDT.  

Adding onSortChange to be consumed in that SortHeaderCell should fix the issue.  If that works for you we'd appreciate it if you could put up a PR with the fix to the example on our repo [here](https://github.com/schrodinger/fixed-data-table-2).  Thanks!

**Comment by wcjordan** [comment]
I've fixed this in the FDT2 examples with this PR: https://github.com/schrodinger/fixed-data-table-2/pull/59

**Comment by roblapp** [comment]
This is still an issue. I am having this problem as well. I am not sure what wcjordan meant by 'Adding onSortChange to be consumed in that SortHeaderCell should fix the issue'. Do he mean to move the [_onSortChange ](https://github.com/facebook/fixed-data-table/blob/master/examples/SortExample.js#L105) function from the SortExample class to the SortCellHeader class?

**Comment by wcjordan** [comment]
Here's an example
```
var {onSortChange, sortDir, children, ...props} = this.props;
return <Cell {...props}>
...
```

The examples in this repo are unfortunately out of date.  I recommend copying from the [maintained fork](https://github.com/schrodinger/fixed-data-table-2/).  See: https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/SortExample.js

**Comment by roblapp** [comment]
@wcjordan Ah I see. Thanks for showing me that.
