### ISSUE TITLE
Error when height is not an integers

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#80]
Whenever I scroll to the bottom of a table, infinite loop occurs:

```
Uncaught RangeError: Maximum call stack size exceededmain.js:33125 escapeUserProvidedKeymain.js:33139 wrapUserProvidedKeymain.js:33112 getComponentKeymain.js:33188 traverseAllChildrenImplmain.js:33304 traverseAllChildrenmain.js:75060 flattenChildrenmain.js:69203 ReactChildReconciler.updateChildrenmain.js:71568 ReactMultiChild.Mixin._updateChildrenmain.js:71542 ReactMultiChild.Mixin.updateChildrenmain.js:18193 ReactDOMComponent.Mixin._updateDOMChildrenmain.js:18044 ReactDOMComponent.Mixin.updateComponentmain.js:18028 ReactDOMComponent.Mixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:30818 ReactCompositeComponentMixin._updateRenderedComponentmain.js:30797 ReactCompositeComponentMixin._performComponentUpdatemain.js:30717 ReactCompositeComponentMixin.updateComponentmain.js:6618 ReactPerf.measure.wrappermain.js:30581 ReactCompositeComponentMixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:30818 ReactCompositeComponentMixin._updateRenderedComponentmain.js:30797 ReactCompositeComponentMixin._performComponentUpdatemain.js:30717 ReactCompositeComponentMixin.updateComponentmain.js:6618 ReactPerf.measure.wrappermain.js:30581 ReactCompositeComponentMixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:69216 ReactChildReconciler.updateChildrenmain.js:71568 ReactMultiChild.Mixin._updateChildrenmain.js:71542 ReactMultiChild.Mixin.updateChildrenmain.js:18193 ReactDOMComponent.Mixin._updateDOMChildrenmain.js:18044 ReactDOMComponent.Mixin.updateComponentmain.js:18028 ReactDOMComponent.Mixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:30818 ReactCompositeComponentMixin._updateRenderedComponentmain.js:30797 ReactCompositeComponentMixin._performComponentUpdatemain.js:30717 ReactCompositeComponentMixin.updateComponentmain.js:6618 ReactPerf.measure.wrappermain.js:30581 ReactCompositeComponentMixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:69216 ReactChildReconciler.updateChildrenmain.js:71568 ReactMultiChild.Mixin._updateChildrenmain.js:71542 ReactMultiChild.Mixin.updateChildrenmain.js:18193 ReactDOMComponent.Mixin._updateDOMChildrenmain.js:18044 ReactDOMComponent.Mixin.updateComponentmain.js:18028 ReactDOMComponent.Mixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:30818 ReactCompositeComponentMixin._updateRenderedComponentmain.js:30797 ReactCompositeComponentMixin._performComponentUpdatemain.js:30717 ReactCompositeComponentMixin.updateComponentmain.js:6618 ReactPerf.measure.wrappermain.js:30581 ReactCompositeComponentMixin.receiveComponentmain.js:13740 ReactReconciler.receiveComponentVM6932:118 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.receiveComponentmain.js:30818 ReactCompositeComponentMixin._updateRenderedComponentmain.js:30797 ReactCompositeComponentMixin._performComponentUpdatemain.js:30717 ReactCompositeComponentMixin.updateComponentmain.js:6618 ReactPerf.measure.wrappermain.js:30614 ReactCompositeComponentMixin.performUpdateIfNecessarymain.js:13758 ReactReconciler.performUpdateIfNecessaryVM6932:112 __REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.performUpdateIfNecessarymain.js:4999 runBatchedUpdatesmain.js:15590 Mixin.performmain.js:15590 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.performmain.js:4943 assign.performmain.js:5023 flushBatchedUpdatesmain.js:6618 ReactPerf.measure.wrappermain.js:4899 NESTED_UPDATES.closemain.js:15663 Mixin.closeAllmain.js:15604 Mixin.perform
```

**Comment by gsklee** [comment]
Screenshots:

First error message:

![1](http://i.imgur.com/9Wgf3AN.png)
![2](http://i.imgur.com/AQXdUd2.png)
![3](http://i.imgur.com/7gRLcWh.png)
![4](http://i.imgur.com/Lba7s41.png)

Second error message:

![5](http://i.imgur.com/Nmif3Z5.png)
![6](http://i.imgur.com/BnmhCTn.png)
![7](http://i.imgur.com/1LUATsp.png)
![8](http://i.imgur.com/iog9rJ3.png)

**Comment by gsklee** [comment]
Found the reason - if `height` etc. are not integers this will cause the problem. The reason that they're not integers can be that they're calculated; in my specific case I calculate my height using the golden ratio.

Example:

http://jsbin.com/biwazetufo/5/edit?html,js,output

**Comment by pieterv** [comment]
Hey @gsklee Thanks for the issue, this sounds pretty easy to fix, we should just force intergers when the value comes in :P

**Comment by gsklee** [comment]
@pieterv Did a quick fix, hopefully that's all about it

**Comment by ehzhang** [comment]
This has been fixed in v0.4.0! Thanks!

**Comment by iamdoron** [comment]
it can still happen (saw it on 0.6.0) if rowHeightGetter returns non-integers
